// <auto-generated />
using System;
using LZRStatsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LZRStatsApi.Migrations
{
    [DbContext(typeof(LzrStatsContext))]
    [Migration("20200217205328_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LZRStatsApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("LZRStatsApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Player637175732079872749",
                            GamesPlayed = 2,
                            JerseyNumber = 1,
                            LastName = "Lastname637175732079873310",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Player1274351464159750740",
                            GamesPlayed = 4,
                            JerseyNumber = 2,
                            LastName = "Lastname1274351464159750802",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Player1911527196239626374",
                            GamesPlayed = 6,
                            JerseyNumber = 3,
                            LastName = "Lastname1911527196239626407",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Player2548702928319501912",
                            GamesPlayed = 8,
                            JerseyNumber = 4,
                            LastName = "Lastname2548702928319501940",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Player3185878660399377460",
                            GamesPlayed = 10,
                            JerseyNumber = 5,
                            LastName = "Lastname3185878660399377495",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Player3823054392479253060",
                            GamesPlayed = 12,
                            JerseyNumber = 6,
                            LastName = "Lastname3823054392479253102",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Player4460230124559128668",
                            GamesPlayed = 14,
                            JerseyNumber = 7,
                            LastName = "Lastname4460230124559128717",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Player5097405856639004304",
                            GamesPlayed = 16,
                            JerseyNumber = 8,
                            LastName = "Lastname5097405856639004360",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Player5734581588718879968",
                            GamesPlayed = 18,
                            JerseyNumber = 9,
                            LastName = "Lastname5734581588718880022",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Player6371757320798755670",
                            GamesPlayed = 20,
                            JerseyNumber = 10,
                            LastName = "Lastname6371757320798755740",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Player7008933052878631391",
                            GamesPlayed = 22,
                            JerseyNumber = 11,
                            LastName = "Lastname7008933052878631457",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Player7646108784958507128",
                            GamesPlayed = 24,
                            JerseyNumber = 12,
                            LastName = "Lastname7646108784958507212",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Player8283284517038382904",
                            GamesPlayed = 26,
                            JerseyNumber = 13,
                            LastName = "Lastname8283284517038382982",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Player8920460249118258694",
                            GamesPlayed = 28,
                            JerseyNumber = 14,
                            LastName = "Lastname8920460249118258792",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Player-8889108092511417091",
                            GamesPlayed = 30,
                            JerseyNumber = 15,
                            LastName = "Lastname-8889108092511416941",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Player-8251932360431541152",
                            GamesPlayed = 32,
                            JerseyNumber = 16,
                            LastName = "Lastname-8251932360431541024",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Player-7614756628351665243",
                            GamesPlayed = 34,
                            JerseyNumber = 17,
                            LastName = "Lastname-7614756628351665124",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Player-6977580896271789250",
                            GamesPlayed = 36,
                            JerseyNumber = 18,
                            LastName = "Lastname-6977580896271789106",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Player-6340405164191913278",
                            GamesPlayed = 38,
                            JerseyNumber = 19,
                            LastName = "Lastname-6340405164191913145",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Player-5703229432112037276",
                            GamesPlayed = 40,
                            JerseyNumber = 20,
                            LastName = "Lastname-5703229432112037136",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Player-5066053700032161244",
                            GamesPlayed = 42,
                            JerseyNumber = 21,
                            LastName = "Lastname-5066053700032161097",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Player-4428877967952284038",
                            GamesPlayed = 44,
                            JerseyNumber = 22,
                            LastName = "Lastname-4428877967952283774",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Player-3791702235872407779",
                            GamesPlayed = 46,
                            JerseyNumber = 23,
                            LastName = "Lastname-3791702235872407595",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Player-3154526503792531552",
                            GamesPlayed = 48,
                            JerseyNumber = 24,
                            LastName = "Lastname-3154526503792531384",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Player-2517350771712655366",
                            GamesPlayed = 50,
                            JerseyNumber = 25,
                            LastName = "Lastname-2517350771712655191",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Player-1880175039632779152",
                            GamesPlayed = 52,
                            JerseyNumber = 26,
                            LastName = "Lastname-1880175039632778970",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Player-1242999307552902883",
                            GamesPlayed = 54,
                            JerseyNumber = 27,
                            LastName = "Lastname-1242999307552902694",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Player-605823575473026612",
                            GamesPlayed = 56,
                            JerseyNumber = 28,
                            LastName = "Lastname-605823575473026416",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Player31352156606849716",
                            GamesPlayed = 58,
                            JerseyNumber = 29,
                            LastName = "Lastname31352156606849919",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Player668527888686726044",
                            GamesPlayed = 60,
                            JerseyNumber = 30,
                            LastName = "Lastname668527888686726254",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Player1305703620766602400",
                            GamesPlayed = 62,
                            JerseyNumber = 31,
                            LastName = "Lastname1305703620766602617",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Player1942879352846478784",
                            GamesPlayed = 64,
                            JerseyNumber = 32,
                            LastName = "Lastname1942879352846479008",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Player2580055084926355196",
                            GamesPlayed = 66,
                            JerseyNumber = 33,
                            LastName = "Lastname2580055084926355394",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Player3217230817006231738",
                            GamesPlayed = 68,
                            JerseyNumber = 34,
                            LastName = "Lastname3217230817006231976",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Player3854406549086108209",
                            GamesPlayed = 70,
                            JerseyNumber = 35,
                            LastName = "Lastname3854406549086108454",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Player4491582281165984708",
                            GamesPlayed = 72,
                            JerseyNumber = 36,
                            LastName = "Lastname4491582281165984960",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Player5128758013245861235",
                            GamesPlayed = 74,
                            JerseyNumber = 37,
                            LastName = "Lastname5128758013245861457",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Player5765933745325737752",
                            GamesPlayed = 76,
                            JerseyNumber = 38,
                            LastName = "Lastname5765933745325738018",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Player6403109477405614295",
                            GamesPlayed = 78,
                            JerseyNumber = 39,
                            LastName = "Lastname6403109477405614568",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Player7040285209485490904",
                            GamesPlayed = 80,
                            JerseyNumber = 40,
                            LastName = "Lastname7040285209485491184",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Player7677460941565367541",
                            GamesPlayed = 82,
                            JerseyNumber = 41,
                            LastName = "Lastname7677460941565367787",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Player8314636673645244164",
                            GamesPlayed = 84,
                            JerseyNumber = 42,
                            LastName = "Lastname8314636673645244458",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Player8951812405725120856",
                            GamesPlayed = 86,
                            JerseyNumber = 43,
                            LastName = "Lastname8951812405725121114",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Player-8857755935904554084",
                            GamesPlayed = 88,
                            JerseyNumber = 44,
                            LastName = "Lastname-8857755935904550124",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Player-8220580203824673332",
                            GamesPlayed = 90,
                            JerseyNumber = 45,
                            LastName = "Lastname-8220580203824672972",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Player-7583404471744796376",
                            GamesPlayed = 92,
                            JerseyNumber = 46,
                            LastName = "Lastname-7583404471744796054",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Player-6946228739664919435",
                            GamesPlayed = 94,
                            JerseyNumber = 47,
                            LastName = "Lastname-6946228739664919106",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Player-6309053007585042464",
                            GamesPlayed = 96,
                            JerseyNumber = 48,
                            LastName = "Lastname-6309053007585042128",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Player-5671877275505165463",
                            GamesPlayed = 98,
                            JerseyNumber = 49,
                            LastName = "Lastname-5671877275505165120",
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("LZRStatsApi.Models.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Blocks")
                        .HasColumnType("int");

                    b.Property<int>("DefensiveRebounds")
                        .HasColumnType("int");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int");

                    b.Property<int>("FG2Attempted")
                        .HasColumnType("int");

                    b.Property<int>("FG2Made")
                        .HasColumnType("int");

                    b.Property<int>("FG3Attempted")
                        .HasColumnType("int");

                    b.Property<int>("FG3Made")
                        .HasColumnType("int");

                    b.Property<int>("FTAttempted")
                        .HasColumnType("int");

                    b.Property<int>("FTMade")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("OffensiveRebounds")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Steals")
                        .HasColumnType("int");

                    b.Property<int>("TotalRebounds")
                        .HasColumnType("int");

                    b.Property<int>("Turnovers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("LZRStatsApi.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Losses = 0,
                            Name = "Team637175732079836597",
                            Wins = 1
                        },
                        new
                        {
                            Id = 2,
                            Losses = 1,
                            Name = "Team1274351464159739116",
                            Wins = 2
                        },
                        new
                        {
                            Id = 3,
                            Losses = 2,
                            Name = "Team1911527196239608887",
                            Wins = 3
                        },
                        new
                        {
                            Id = 4,
                            Losses = 3,
                            Name = "Team2548702928319478568",
                            Wins = 4
                        },
                        new
                        {
                            Id = 5,
                            Losses = 4,
                            Name = "Team3185878660399348250",
                            Wins = 5
                        },
                        new
                        {
                            Id = 6,
                            Losses = 5,
                            Name = "Team3823054392479217972",
                            Wins = 6
                        },
                        new
                        {
                            Id = 7,
                            Losses = 6,
                            Name = "Team4460230124559087690",
                            Wins = 7
                        },
                        new
                        {
                            Id = 8,
                            Losses = 7,
                            Name = "Team5097405856638957424",
                            Wins = 8
                        },
                        new
                        {
                            Id = 9,
                            Losses = 8,
                            Name = "Team5734581588718827165",
                            Wins = 9
                        },
                        new
                        {
                            Id = 10,
                            Losses = 9,
                            Name = "Team6371757320798696950",
                            Wins = 10
                        },
                        new
                        {
                            Id = 11,
                            Losses = 10,
                            Name = "Team7008933052878566744",
                            Wins = 11
                        },
                        new
                        {
                            Id = 12,
                            Losses = 11,
                            Name = "Team7646108784958436532",
                            Wins = 12
                        },
                        new
                        {
                            Id = 13,
                            Losses = 12,
                            Name = "Team8283284517038306334",
                            Wins = 13
                        },
                        new
                        {
                            Id = 14,
                            Losses = 13,
                            Name = "Team8920460249118176150",
                            Wins = 14
                        },
                        new
                        {
                            Id = 15,
                            Losses = 14,
                            Name = "Team-8889108092511505636",
                            Wins = 15
                        },
                        new
                        {
                            Id = 16,
                            Losses = 15,
                            Name = "Team-8251932360431634000",
                            Wins = 16
                        },
                        new
                        {
                            Id = 17,
                            Losses = 16,
                            Name = "Team-7614756628351763826",
                            Wins = 17
                        },
                        new
                        {
                            Id = 18,
                            Losses = 17,
                            Name = "Team-6977580896271892660",
                            Wins = 18
                        },
                        new
                        {
                            Id = 19,
                            Losses = 18,
                            Name = "Team-6340405164192022471",
                            Wins = 19
                        },
                        new
                        {
                            Id = 20,
                            Losses = 19,
                            Name = "Team-5703229432112152356",
                            Wins = 20
                        },
                        new
                        {
                            Id = 21,
                            Losses = 20,
                            Name = "Team-5066053700032282225",
                            Wins = 21
                        },
                        new
                        {
                            Id = 22,
                            Losses = 21,
                            Name = "Team-4428877967952412078",
                            Wins = 22
                        },
                        new
                        {
                            Id = 23,
                            Losses = 22,
                            Name = "Team-3791702235872541915",
                            Wins = 23
                        },
                        new
                        {
                            Id = 24,
                            Losses = 23,
                            Name = "Team-3154526503792671760",
                            Wins = 24
                        },
                        new
                        {
                            Id = 25,
                            Losses = 24,
                            Name = "Team-2517350771712801566",
                            Wins = 25
                        },
                        new
                        {
                            Id = 26,
                            Losses = 25,
                            Name = "Team-1880175039632931356",
                            Wins = 26
                        },
                        new
                        {
                            Id = 27,
                            Losses = 26,
                            Name = "Team-1242999307553061157",
                            Wins = 27
                        },
                        new
                        {
                            Id = 28,
                            Losses = 27,
                            Name = "Team-605823575473190944",
                            Wins = 28
                        },
                        new
                        {
                            Id = 29,
                            Losses = 28,
                            Name = "Team31352156606679341",
                            Wins = 29
                        },
                        new
                        {
                            Id = 30,
                            Losses = 29,
                            Name = "Team668527888686549614",
                            Wins = 30
                        },
                        new
                        {
                            Id = 31,
                            Losses = 30,
                            Name = "Team1305703620766419872",
                            Wins = 31
                        },
                        new
                        {
                            Id = 32,
                            Losses = 31,
                            Name = "Team1942879352846290176",
                            Wins = 32
                        },
                        new
                        {
                            Id = 33,
                            Losses = 32,
                            Name = "Team2580055084926160463",
                            Wins = 33
                        },
                        new
                        {
                            Id = 34,
                            Losses = 33,
                            Name = "Team3217230817006030866",
                            Wins = 34
                        },
                        new
                        {
                            Id = 35,
                            Losses = 34,
                            Name = "Team3854406549085901254",
                            Wins = 35
                        },
                        new
                        {
                            Id = 36,
                            Losses = 35,
                            Name = "Team4491582281165771588",
                            Wins = 36
                        },
                        new
                        {
                            Id = 37,
                            Losses = 36,
                            Name = "Team5128758013245641973",
                            Wins = 37
                        },
                        new
                        {
                            Id = 38,
                            Losses = 37,
                            Name = "Team5765933745325512298",
                            Wins = 38
                        },
                        new
                        {
                            Id = 39,
                            Losses = 38,
                            Name = "Team6403109477405382674",
                            Wins = 39
                        },
                        new
                        {
                            Id = 40,
                            Losses = 39,
                            Name = "Team7040285209485253064",
                            Wins = 40
                        },
                        new
                        {
                            Id = 41,
                            Losses = 40,
                            Name = "Team7677460941565123468",
                            Wins = 41
                        },
                        new
                        {
                            Id = 42,
                            Losses = 41,
                            Name = "Team8314636673644993886",
                            Wins = 42
                        },
                        new
                        {
                            Id = 43,
                            Losses = 42,
                            Name = "Team8951812405724864275",
                            Wins = 43
                        },
                        new
                        {
                            Id = 44,
                            Losses = 43,
                            Name = "Team-8857755935904816896",
                            Wins = 44
                        },
                        new
                        {
                            Id = 45,
                            Losses = 44,
                            Name = "Team-8220580203824946347",
                            Wins = 45
                        },
                        new
                        {
                            Id = 46,
                            Losses = 45,
                            Name = "Team-7583404471745075872",
                            Wins = 46
                        },
                        new
                        {
                            Id = 47,
                            Losses = 46,
                            Name = "Team-6946228739665205336",
                            Wins = 47
                        },
                        new
                        {
                            Id = 48,
                            Losses = 47,
                            Name = "Team-6309053007585334832",
                            Wins = 48
                        },
                        new
                        {
                            Id = 49,
                            Losses = 48,
                            Name = "Team-5671877275505464265",
                            Wins = 49
                        });
                });

            modelBuilder.Entity("LZRStatsApi.Models.TeamGame", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PointsScored")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("TeamGame");
                });

            modelBuilder.Entity("LZRStatsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Super",
                            LastName = "Admin",
                            Password = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("LZRStatsApi.Models.Player", b =>
                {
                    b.HasOne("LZRStatsApi.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LZRStatsApi.Models.PlayerStats", b =>
                {
                    b.HasOne("LZRStatsApi.Models.Game", "Game")
                        .WithMany("PlayerStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LZRStatsApi.Models.Player", "Player")
                        .WithMany("PlayerStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LZRStatsApi.Models.TeamGame", b =>
                {
                    b.HasOne("LZRStatsApi.Models.Game", "Game")
                        .WithMany("TeamGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LZRStatsApi.Models.Team", "Team")
                        .WithMany("TeamGames")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
